<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\SiteController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PortfolioController;
use App\Http\Controllers\Admin\BotController;
use App\Http\Controllers\Admin\ThemeController;
use App\Http\Controllers\Admin\TemplateController;
use App\Http\Controllers\Admin\EmailController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\WebServiceController;
use App\Http\Controllers\Admin\UserUpdateController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PluginController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ToolController;
use App\Http\Controllers\Admin\LogoutController;
use App\Http\Controllers\Site\HomeController;
use App\Http\Controllers\Site\GalleryController;
use App\Http\Controllers\Site\AboutController;
use App\Http\Controllers\Site\NewsController as SiteNewsController;
use App\Http\Controllers\Site\MediaController;
use App\Http\Controllers\Site\HelpController;
use App\Http\Controllers\Site\ProjectsController;
use App\Http\Controllers\Site\AuctionController;
use App\Http\Controllers\Site\ContactsController;

Route::get('/', [HomeController::class, 'index']);
Route::get('gallery', [GalleryController::class, 'index']);
Route::get('about', [AboutController::class, 'index']);
Route::get('news', [SiteNewsController::class, 'index']);
Route::get('media', [MediaController::class, 'index']);
Route::get('help', [HelpController::class, 'index']);
Route::get('projects', [ProjectsController::class, 'index']);
Route::get('auction', [AuctionController::class, 'index']);
Route::get('contacts', [ContactsController::class, 'index']);

Route::prefix('admin')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index']);
    Route::get('site', [SiteController::class, 'index']);
    Route::get('news', [NewsController::class, 'index']);
    Route::get('page', [PageController::class, 'index']);
    Route::get('portfolio', [PortfolioController::class, 'index']);
    Route::get('bot', [BotController::class, 'index']);
    Route::get('theme', [ThemeController::class, 'index']);
    Route::get('template', [TemplateController::class, 'index']);
    Route::get('email', [EmailController::class, 'index']);
    Route::get('product', [ProductController::class, 'index']);
    Route::get('webservice', [WebServiceController::class, 'index']);
    Route::get('user-update', [UserUpdateController::class, 'index']);
    Route::get('payment', [PaymentController::class, 'index']);
    Route::get('user', [UserController::class, 'index']);
    Route::get('plugin', [PluginController::class, 'index']);
    Route::get('setting', [SettingController::class, 'index']);
    Route::get('tool', [ToolController::class, 'index']);
    Route::get('logout', [LogoutController::class, 'index']);
});
